import { CHATYI_ROBOT } from "@/ai/constant";

export const yiModelValue = (models) => {
  return {
    Model: {
      ID: "model",
      Title: "模型 (model)",
      SubTitle: "01.AI 零一万物 模型",
      defaultValue: "",
      options: models.filter((t) => t.provider.convId === CHATYI_ROBOT),
    },
    OpenaiUrl: {
      ID: "openaiUrl",
      Title: "接口地址",
      SubTitle: "除默认地址外，必须包含 http(s)://",
      Placeholder: "https://api.lingyiwanwu.com/",
      defaultValue: "",
      password: true,
    },
    Token: {
      ID: "token",
      Title: "API Key",
      SubTitle: "使用自己的 01.AI 零一万物 API Key",
      Placeholder: "ZeroOne API Key",
      defaultValue: "",
      password: true,
    },
    Temperature: {
      ID: "temperature",
      Title: "随机性 (temperature)",
      SubTitle: "值越大，回复越随机",
      defaultValue: "",
      Range: true,
      step: 0.1,
      min: 0,
      max: 1,
    },
    TopP: {
      ID: "top_p",
      Title: "核采样 (top_p)",
      SubTitle: "与随机性类似，但不要和随机性一起更改",
      defaultValue: "",
      Range: true,
      step: 0.1,
      min: 0,
      max: 1,
    },
    MaxTokens: {
      ID: "max_tokens",
      Title: "单次回复限制 (max_tokens)",
      SubTitle: "单次交互所用的最大 Token 数",
      defaultValue: "",
      Number: true,
      min: 1024,
      max: 8192,
    },
    PresencePenalty: {
      ID: "presence_penalty",
      Title: "话题新鲜度 (presence_penalty)",
      SubTitle: "值越大，越有可能扩展到新话题",
      defaultValue: "",
      Range: true,
      step: 0.1,
      min: 0,
      max: 2,
    },
    FrequencyPenalty: {
      ID: "frequency_penalty",
      Title: "频率惩罚度 (frequency_penalty)",
      SubTitle: "值越大，越有可能降低重复字词",
      defaultValue: "",
      Range: true,
      step: 0.1,
      min: 0,
      max: 2,
    },
    historyMessageCount: {
      ID: "historyMessageCount",
      Title: "附带历史消息数",
      SubTitle: "每次请求携带的历史消息数",
      defaultValue: "",
      Range: true,
      step: 1,
      min: 1,
      max: 24,
    },
  };
};
